### Search a film or tv show
GET http://localhost:8080/v1/medialib/search?
    query=pluribus

### Add a search result to watchlist
POST http://localhost:8080/v1/medialib/watchlist
Content-Type: application/json

{
  "type": "TV_SHOW",
  "externalId": "436457"
}

### Get all items of watchlist
GET http://localhost:8080/v1/medialib/watchlist
Content-Type: application/json

### Get a item of watchlist by id
GET http://localhost:8080/v1/medialib/watchlist/152
Content-Type: application/json

### Modify a film or tv show (mark to download o as watched)
PUT http://localhost:8080/v1/medialib/watchlist/152
Content-Type: application/json

{
  "markToDownload": true,
  "markAsWatched": false
}