openapi: "3.0.0"
info:
  title: "Rpi Sweet Home"
  version: "1.0"

servers:
  - url: "http://localhost:8080"

tags:
  - name: Search
    description: To search in provider
  - name: Watchlist
    description: Add or get media items from watchlist
  - name: Movies
    description: Movies or films
  - name: TvShows
    description: Tv shows
  - name: QualityTags
    description: Manage quality tags for media items

paths:
  /v1/medialib/search:
    $ref: "services/search.yml#/schemas/SearchApi"
  /v1/medialib/watchlist:
    $ref: "services/watchlist.yml#/schemas/WatchlistApi"
  /v1/medialib/movies:
    $ref: "services/movies.yml#/schemas/MovieApi"
  /v1/medialib/movies/{id}:
    $ref: "services/movies.yml#/schemas/MovieByItemApi"
  /v1/medialib/tvshows:
    $ref: "services/tvshows.yml#/schemas/TvShowApi"
  /v1/medialib/tvshows/{id}:
    $ref: "services/tvshows.yml#/schemas/TvShowByItemApi"
  /v1/medialib/tvshows/{id}/seasons/{season}:
    $ref: "services/tvshows.yml#/schemas/SeasonApi"
  /v1/medialib/tvshows/{id}/seasons/{season}/episodes/{episode}:
    $ref: "services/tvshows.yml#/schemas/EpisodeApi"
  /v1/medialib/quality-tags:
    $ref: "services/quality-tags.yml#/schemas/QualityTagApi"
  /v1/medialib/quality-tags/{id}:
    $ref: "services/quality-tags.yml#/schemas/QualityTagByItemApi"

