spring:
  application:
    name: rpi-sweet-home
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:15432/rpi-sweet-home}
    username: ${DB_USERNAME:rpi-sweet-home}
    password: ${DB_PASSWORD:admin1234!}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


rpi-sweet-home:
  executors:
    io-executor:
      type: ${EXECUTORS_IO_TYPE:VIRTUAL_THREAD_POOL}
      threads: ${EXECUTORS_IO_THREADS:5}
  tvdb:
    base-url: ${TVDB_API_BASE_URL:https://api.thetvdb.com/v4}
    api-key: ${TVDB_API_KEY:}
    limit: ${TVDB_API_LIMIT:100}